[project]
name = "supabase-ai-query-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=2.8.1",
    "psycopg2>=2.9.11",
    "sqlalchemy>=2.0.44",
    "streamlit>=1.51.0",
]
